#!/bin/bash -e

# source env so that we have all secrets setup
source <(sed 's/^/export /' ./env)

# deps are needed
mix deps.get

# build the js files
(cd assets && npm install --no-progress && ./node_modules/brunch/bin/brunch build --production)

# build release
mix phoenix.digest
mix release
